version: '3.8'
services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - ../.env

  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bot
    env_file:
      - ../.env

